model:
  type: simple
  in_channels: 1
  out_ch: 1
  ch: 128
  ch_mult: [1, 1, 2, 2, 4, 4]
  num_res_blocks: 2
  attn_resolutions: [16]
  dropout: 0.0
  var_type: fixedlarge
  resamp_with_conv: true
  ema_rate: 0.999
  ema: true

diffusion:
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  num_diffusion_timesteps: 1000

data:
  dataset: ULTRASOUND
  image_size: 512
  channels: 1
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: false
  rescaled: true
  num_workers: 4

sampling:
  method: ddpm
  batch_size: 1
  last_only: true
  sample_step: 1
